#goal definition
robot_module_msgs/CartesianSpaceDMP DMP
geometry_msgs/Transform BaseFrame
---
#result definition
float32[] position
float32[] orientation
---
#feedback
float32[] position
float32[] orientation
