#goal definition
sensor_msgs/JointState joints
float32 speed #max target speed 
float32 acc  #max target acceleration 
---
#result definition
sensor_msgs/JointState final_joints
bool fully_succeeded
---
#feedback
sensor_msgs/JointState joints
float32 joint_diff
