string toolName # A string specifying the name of the tool
float64[] toolPosition # The positional offset of the tool
float64[] toolRotation # The rotational offset of the tool in quaternion
float64 weight # the weight of the tool in kg
---
bool success # indicate successful run of triggered service
string message # informational, e.g. for error messages
